# Generated by Django 4.1 on 2022-08-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='detail_user',
            field=models.CharField(default='', max_length=500),
        ),
    ]
